### ISSUE TITLE
Country data not populating on the web interface at all

### ISSUE THREAD

**Issue by da667** [int13h/squert#66]
Hello,

I'm relatively new to squert and while the interface looks amazing, I'm running into an issue: I can't get any country data to populate anywhere on the web interface. I'm not entirely sure where the issue lies.

Here's what I have done:
-ran ip2c.tcl.
--states that it updated the various *NIC databases

-ran mysql -uroot -p -D sguildb -e "select count(*) from ip2c;"
--returns 152,145 confirm that ip2c table isn't empty, but I have no idea whether or not this number is accurate.

Is there anything else I can do to troubleshoot this?

**Comment by int13h** [comment]
Does the mappings table exist? That is where the actual translations end up.

Did you perform this step:

14) Create a scheduled task to keep the mappings tables up to date:

*/5 * * * * /usr/local/bin/php -e /usr/local/www/squert/.inc/ip2c.php 1 > /dev/null 2>&1

This entry updates the database every 5 minutes. Make sure you use the correct paths to php and ip2c.php.


Let me know how you make out.

**Comment by da667** [comment]
figured out my issue:
"ip2c.php" must be ran with the "0" option for the first run. I'm not sure
if that was in the documentation, or if I skipped it. ran php -e
/var/www/squert/.inc/ip2c.php and country information was populated
correctly. You may mark this as closed at your leisure. Thanks!

On Tue, Feb 10, 2015 at 9:06 PM, Paul Halliday <notifications@github.com>
wrote:

> Does the mappings table exist? That is where the actual translations end
> up.
>
> Did you perform this step:
>
> 14) Create a scheduled task to keep the mappings tables up to date:
>
> */5 * * * * /usr/local/bin/php -e /usr/local/www/squert/.inc/ip2c.php 1 >
> /dev/null 2>&1
>
> This entry updates the database every 5 minutes. Make sure you use the
> correct paths to php and ip2c.php.
>
> Let me know how you make out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/int13h/squert/issues/66#issuecomment-73823361>.
>



-- 
when does reality end? when does fantasy begin?

**Comment by int13h** [comment]
Good.

Be sure to add the cronjob mentioned above to keep things in sync.
